### ISSUE TITLE
Test: Unit Test Coverage for AVS/Middleware Contracts

### ISSUE THREAD

**Issue by ChaoticWalrus** [Layr-Labs/eigenlayer-middleware#22]
## Description
Master ticket covering achieving good unit test coverage for all contracts in this repo.

### Action Items
TBD, needs to be broken down into smaller items (at least per-contract)

### Blocking Issues
N/A
```[tasklist]
### Tasks
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/94
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/86
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/88
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/89
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/92
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/93
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/90
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/91
- [ ] https://github.com/Layr-Labs/eigenlayer-middleware/issues/130
```

**Comment by 8sunyuan** [comment]
Completed unit testing as of this commit https://github.com/Layr-Labs/eigenlayer-middleware/tree/2856834e1f90133ed692cbc25f2880e3769c5c80
